steps:
  - id: 'branch name'
    name: 'alpine'
    entrypoint: 'sh'  
    args: 
    - '-c'
    - | 
        echo "***********************"
        echo "$BRANCH_NAME"
        echo "***********************"

  - id: 'tf-plan'
    name: 'hashicorp/terraform:0.14.5'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        if [ "$BRANCH_NAME" == "dev" ]; then
          cd dev
          terraform init
          terraform plan
        else
          echo ERROR: "$BRANCH_NAME" unknown environment
        fi 

